measures() returns only relevant spanners (#826)
* measures() returns only relevant spanners

* line length

* StaffGroup is no longer relevant when a single staff's measures extracted

* Coveralls says this doesn't run anymore
Which makes sense, this was the error:
music21.exceptions21.StreamException: cannot find object (<music21.note.Note E->) in Stream

* Revert "Coveralls says this doesn't run anymore"

This reverts commit 81c773cf49cf155edd534406d157dcdf00f972b2.